In [1]:
import numpy as np
from numpy.lib.stride_tricks import as_strided


def sliding_windows(arr, window_shape, step=1):
    """
    从二维数组中提取滑动窗口，每个窗口展平成一维数组，所有窗口形成二维数组。
    
    参数:
    arr -- 输入的二维数组
    window_shape -- 窗口的形状，例如(2, 3)
    step -- 窗口滑动的步长，默认为1    返回:
    一个二维数组，其中每行是一个展平后的滑动窗口
    """
    rows, cols = arr.shape
    window_rows, window_cols = window_shape
    new_shape = ((rows - window_rows) // step + 1,
                 (cols - window_cols) // step + 1,
                 window_rows,
                 window_cols)
    new_strides = (arr.strides[0]*step, arr.strides[1]*step) + arr.strides

    strided_arr = as_strided(arr, shape=new_shape, strides=new_strides)
    return strided_arr.reshape(-1, window_rows * window_cols)


# 示例使用
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# 提取 2x2 的滑窗口
window_shape = (2, 2)
result = sliding_windows(arr, window_shape)

print(result)

[[ 1  2  5  6]
 [ 2  3  6  7]
 [ 3  4  7  8]
 [ 5  6  9 10]
 [ 6  7 10 11]
 [ 7  8 11 12]]


In [2]:
arr=np.arange(10)
idx=np.array([[3,4,5],[3,4,5]])
print(arr[idx])

[[3 4 5]
 [3 4 5]]
